export const APPLICATION_LIST_SUCCESS = 'APPLICATION_LIST_SUCCESS';
export const APPLICATION_ACTION_FAIL = 'APPLICATION_ACTION_FAIL';
export const APPLICATION_ACTION_SUCCESS = 'APPLICATION_ACTION_SUCCESS';
